name: dart_code_linter_analyzer_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 3.1.0-beta.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_linter: 3.1.0-beta.2

dev_dependencies:
  lints: ^1.0.1
