name: "flutter-actions"
on:
  pull_request:
    branches:
      - trunk
jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.13.8
      - name: Install dependencies
        run: dart pub get
      - name: Run Tests
        run: dart test