# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
      - name: Setup Flutter
        uses: bancolombia/flutter-setup-action@v1.1
        with:
          channel: 'stable'
          flutter-version: '3.35.0'
      - name: Install dependencies
        run: dart pub get
      - name: Publish to pub.dev
        run: dart pub publish -f
